# Generated by Django 5.2.5 on 2025-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_category_dish_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
