# Generated by Django 5.2.5 on 2025-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_alter_category_added_on_alter_dish_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
