# Generated by Django 5.2.5 on 2025-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_alter_category_updated_on_alter_dish_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
