site_name: FoodZone Documentation
site_description: A full-featured Django food-ordering web application
site_author: Your Name
site_url: https://your-username.github.io/foodzone/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: orange
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: orange
      accent: deep orange

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sajid-ali-8662b918b

nav:
  - Home: index.md
  - Features: features.md
  - Menu: all_dishes.md
  - About: about.md
  - Register: register.md
  - Login: login.md
  - Dashboard: dashboard.md
  - Contact: contact.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
